
# Colors
[colors]
  [colors.primary]
    foreground = "#dfdfdf"
    background = "#000000"
    dim_foreground = "#7d7d7d"

  [colors.cursor]
    text = "#000000"
    cursor = "#dfdfdf"

  [colors.normal]
    black   = "#000000"
    red     = "#ff0000"
    green   = "#00ff00"
    yellow  = "#ffff00"
    blue    = "#0000ff"
    magenta = "#ff00ff"
    cyan    = "#00ffff"
    white   = "#dfdfdf"

  [colors.bright]
    black   = "#555555"
    red     = "#ff6e6e"
    green   = "#69ff94"
    yellow  = "#ffffa5"
    blue    = "#d6acff"
    magenta = "#ff92df"
    cyan    = "#00dfdf"
    white   = "#ffffff"

# Mouse
[mouse]
hide_when_typing = true

[window]
opacity = 0.8

# Requires 'ttf-jetbrains-mono-nerd' to be installed on Arch.
[font]
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
